### ISSUE TITLE
Cannot start demo project

### ISSUE THREAD

**Issue by jpic** [wq/wq#27]
Hello everybody !

There's currently a version conflict occurring when trying to start the example project as in the README:

```
21/09 2017 14:25:17 jpic@mez /tmp 
$ python3 -m venv venv

21/09 2017 14:25:19 jpic@mez /tmp 
$ . venv/bin/activate

[venv] 21/09 2017 14:25:19 jpic@mez /tmp 
$ pip install wq
Collecting wq
  Downloading wq-1.0.0.tar.gz
Collecting wq.app<1.1.0,>=1.0.0 (from wq)
  Downloading wq.app-1.0.0.tar.gz (1.0MB)
    100% |████████████████████████████████| 1.0MB 555kB/s 
Collecting wq.core<1.1.0,>=1.0.0 (from wq)
  Downloading wq.core-1.0.0.tar.gz
Collecting wq.db<1.1.0,>=1.0.0 (from wq)
  Downloading wq.db-1.0.0.tar.gz
Collecting wq.io<1.1.0,>=1.0.0 (from wq)
  Downloading wq.io-1.0.0.tar.gz
Collecting wq.start<1.1.0,>=1.0.0 (from wq)
  Downloading wq.start-1.0.0.tar.gz (53kB)
    100% |████████████████████████████████| 61kB 848kB/s 
Collecting pyScss>=1.3 (from wq.app<1.1.0,>=1.0.0->wq)
  Downloading pyScss-1.3.5.tar.gz (123kB)
    100% |████████████████████████████████| 133kB 737kB/s 
Collecting compass-stylesheets==0.12.6 (from wq.app<1.1.0,>=1.0.0->wq)
  Downloading compass-stylesheets-0.12.6.tar.gz
Collecting PyYAML (from wq.app<1.1.0,>=1.0.0->wq)
Collecting requests (from wq.app<1.1.0,>=1.0.0->wq)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting pystache (from wq.app<1.1.0,>=1.0.0->wq)
  Downloading pystache-0.5.4.tar.gz (75kB)
    100% |████████████████████████████████| 81kB 776kB/s 
Collecting Pillow (from wq.app<1.1.0,>=1.0.0->wq)
  Using cached Pillow-4.2.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting click<6 (from wq.core<1.1.0,>=1.0.0->wq)
  Downloading click-5.1-py2.py3-none-any.whl (65kB)
    100% |████████████████████████████████| 71kB 913kB/s 
Collecting Django>=1.8 (from wq.db<1.1.0,>=1.0.0->wq)
  Using cached Django-1.11.5-py2.py3-none-any.whl
Collecting djangorestframework>=3.3.3 (from wq.db<1.1.0,>=1.0.0->wq)
  Using cached djangorestframework-3.6.4-py2.py3-none-any.whl
Collecting django-mustache (from wq.db<1.1.0,>=1.0.0->wq)
  Downloading django-mustache-1.1.0.tar.gz
Collecting html-json-forms (from wq.db<1.1.0,>=1.0.0->wq)
  Downloading html-json-forms-1.0.0.tar.gz
Collecting natural-keys>=1.2.0 (from wq.db<1.1.0,>=1.0.0->wq)
  Downloading natural-keys-1.2.1.tar.gz
Collecting swapper (from wq.db<1.1.0,>=1.0.0->wq)
  Downloading swapper-1.1.0.tar.gz
Collecting Markdown (from wq.db<1.1.0,>=1.0.0->wq)
Collecting xlrd (from wq.io<1.1.0,>=1.0.0->wq)
  Using cached xlrd-1.1.0-py2.py3-none-any.whl
Collecting psycopg2 (from wq.start<1.1.0,>=1.0.0->wq)
  Using cached psycopg2-2.7.3.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting xlsconv>=1.0.0 (from wq.start<1.1.0,>=1.0.0->wq)
  Downloading xlsconv-1.0.0.tar.gz
Collecting six (from pyScss>=1.3->wq.app<1.1.0,>=1.0.0->wq)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests->wq.app<1.1.0,>=1.0.0->wq)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->wq.app<1.1.0,>=1.0.0->wq)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->wq.app<1.1.0,>=1.0.0->wq)
  Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests->wq.app<1.1.0,>=1.0.0->wq)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting olefile (from Pillow->wq.app<1.1.0,>=1.0.0->wq)
  Using cached olefile-0.44.zip
Collecting pytz (from Django>=1.8->wq.db<1.1.0,>=1.0.0->wq)
  Using cached pytz-2017.2-py2.py3-none-any.whl
Collecting pyxform (from xlsconv>=1.0.0->wq.start<1.1.0,>=1.0.0->wq)
  Downloading pyxform-0.9.24.tar.gz (891kB)
    100% |████████████████████████████████| 901kB 545kB/s 
Collecting unicodecsv==0.14.1 (from pyxform->xlsconv>=1.0.0->wq.start<1.1.0,>=1.0.0->wq)
Collecting formencode (from pyxform->xlsconv>=1.0.0->wq.start<1.1.0,>=1.0.0->wq)
  Downloading FormEncode-1.3.1.tar.gz (197kB)
    100% |████████████████████████████████| 204kB 757kB/s 
Collecting unittest2 (from pyxform->xlsconv>=1.0.0->wq.start<1.1.0,>=1.0.0->wq)
  Downloading unittest2-1.1.0-py2.py3-none-any.whl (96kB)
    100% |████████████████████████████████| 102kB 779kB/s 
Collecting argparse (from unittest2->pyxform->xlsconv>=1.0.0->wq.start<1.1.0,>=1.0.0->wq)
  Downloading argparse-1.4.0-py2.py3-none-any.whl
Collecting traceback2 (from unittest2->pyxform->xlsconv>=1.0.0->wq.start<1.1.0,>=1.0.0->wq)
  Downloading traceback2-1.4.0-py2.py3-none-any.whl
Collecting linecache2 (from traceback2->unittest2->pyxform->xlsconv>=1.0.0->wq.start<1.1.0,>=1.0.0->wq)
  Downloading linecache2-1.0.0-py2.py3-none-any.whl
Installing collected packages: click, PyYAML, wq.core, six, pyScss, compass-stylesheets, urllib3, chardet, certifi, idna, requests, pystache, olefile, Pillow, wq.app, pytz, Django, djangorestframework, django-mustache, html-json-forms, natural-keys, swapper, Markdown, wq.db, xlrd, wq.io, psycopg2, unicodecsv, formencode, argparse, linecache2, traceback2, unittest2, pyxform, xlsconv, wq.start, wq
  Running setup.py install for wq.core ... done
  Running setup.py install for pyScss ... done
  Running setup.py install for compass-stylesheets ... done
  Running setup.py install for pystache ... done
  Running setup.py install for olefile ... done
  Running setup.py install for wq.app ... done
  Running setup.py install for django-mustache ... done
  Running setup.py install for html-json-forms ... done
  Running setup.py install for natural-keys ... done
  Running setup.py install for swapper ... done
  Running setup.py install for wq.db ... done
  Running setup.py install for wq.io ... done
  Running setup.py install for formencode ... done
  Running setup.py install for pyxform ... done
  Running setup.py install for xlsconv ... done
  Running setup.py install for wq.start ... done
  Running setup.py install for wq ... done
Successfully installed Django-1.11.5 Markdown-2.6.9 Pillow-4.2.1 PyYAML-3.12 argparse-1.4.0 certifi-2017.7.27.1 chardet-3.0.4 click-5.1 compass-stylesheets-0.12.6 django-mustache-1.1.0 djangorestframework-3.6.4 formencode-1.3.1 html-json-forms-1.0.0 idna-2.6 linecache2-1.0.0 natural-keys-1.2.1 olefile-0.44 psycopg2-2.7.3.1 pyScss-1.3.5 pystache-0.5.4 pytz-2017.2 pyxform-0.9.24 requests-2.18.4 six-1.11.0 swapper-1.1.0 traceback2-1.4.0 unicodecsv-0.14.1 unittest2-1.1.0 urllib3-1.22 wq-1.0.0 wq.app-1.0.0 wq.core-1.0.0 wq.db-1.0.0 wq.io-1.0.0 wq.start-1.0.0 xlrd-1.1.0 xlsconv-1.0.0

[venv] 21/09 2017 14:25:50 jpic@mez /tmp 
$ wq start -d myproject.example.com myproject
Traceback (most recent call last):
  File "/tmp/venv/bin/wq", line 11, in <module>
    load_entry_point('wq.core==1.0.0', 'console_scripts', 'wq')()
  File "/tmp/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/tmp/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/tmp/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/tmp/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/tmp/venv/lib/python3.6/site-packages/wq/core/__init__.py", line 48, in <module>
    module.load()
  File "/tmp/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2290, in load
    self.require(*args, **kwargs)
  File "/tmp/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2307, in require
    items = working_set.resolve(reqs, env, installer)
  File "/tmp/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 858, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (xlrd 1.1.0 (/tmp/venv/lib/python3.6/site-packages), Requirement.parse('xlrd==1.0.0'), {'pyxform'})
```

**Comment by sheppard** [comment]
Thanks for reporting this.  wq's xlrd spec is looser than pxyform's, so you should be able to get around this by re-installing pyxform (at least until they release a new version with the update).

**Comment by sheppard** [comment]
The new version of pyxform is out, so closing this issue.
