### ISSUE TITLE
Error on ./manage.py migrate

### ISSUE THREAD

**Issue by chlarsen** [wq/wq#30]
Thank you once more for this great piece of work. I tried to set up the latest 1.0.0 version inside my FreeBSD 10.3 jail using Python 3.6 and following your Ubuntu instructions for the installation itself.
I got around the locale issues surrounding Python 3 on FreeBSD by setting LC and LANG, but got this, when issuing 
``````
./manage.py migrate
``````
from within the virtual environment:
``````
[wq_synalinq] (pts/1)[root@www_py:/usr/local/wq_synalinq/db]# ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/wq_synalinq/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/wq_synalinq/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/local/wq_synalinq/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/wq_synalinq/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/wq_synalinq/lib/python3.6/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/wq_synalinq/lib/python3.6/site-packages/wq/db/rest/__init__.py", line 2, in <module>
    from .routers import ModelRouter, router
  File "/usr/local/wq_synalinq/lib/python3.6/site-packages/wq/db/rest/routers.py", line 560, in <module>
    router = ModelRouter()
  File "/usr/local/wq_synalinq/lib/python3.6/site-packages/wq/db/rest/routers.py", line 49, in __init__
    initkwargs={'suffix': 'List'}
TypeError: __new__() missing 1 required positional argument: 'detail'
``````
I am not sure, where to start - am I missing anything?
Thank you so much for your help,
Chris

**Comment by chlarsen** [comment]
Update: The above error was encountered when using FreeBSD 10.4 inside a jail. The same error occurs with OpenBSD 6.2, just from within the Pyton 3.6 virtualenv.
Any help would be hugely appreciated.
Chris

**Comment by chlarsen** [comment]
More diagnostic work: 
I deduced from the installation instructions for Windows and RedHat & Co, that Python 2 may still be supported, and followed the instructions accordingly. Alas, no joy. I get:
``````
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/wq_io_ghs_idi/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/wq_io_ghs_idi/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/local/wq_io_ghs_idi/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/wq_io_ghs_idi/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/wq_io_ghs_idi/lib/python2.7/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/wq_io_ghs_idi/lib/python2.7/site-packages/wq/db/rest/__init__.py", line 2, in <module>
    from .routers import ModelRouter, router
  File "/usr/local/wq_io_ghs_idi/lib/python2.7/site-packages/wq/db/rest/routers.py", line 560, in <module>
    router = ModelRouter()
  File "/usr/local/wq_io_ghs_idi/lib/python2.7/site-packages/wq/db/rest/routers.py", line 49, in __init__
    initkwargs={'suffix': 'List'}
TypeError: __new__() takes exactly 6 arguments (5 given)
``````
settings_local.py has been completed as advised and is common practice in the Django world.
Any thoughts, ideas?
Thank you!
Chris

**Comment by sheppard** [comment]
Hi, this is fixed in the latest master which I hope to release relatively soon.  In the meantime, you can try adding one extra command after `pip install wq`:

```
pip install https://github.com/wq/wq.db/archive/master.zip
```

**Comment by chlarsen** [comment]
Dear Andrew,
This is wonderful news! Thank you. Will check it out today!
Thank you so much.
Chris

On May 21, 2018 9:19:44 PM UTC, "S. Andrew Sheppard" <notifications@github.com> wrote:
>Hi, this is fixed in the latest master which I hope to release
>relatively soon.  In the meantime, you can try adding one extra command
>after `pip install wq`:
>
>```
>pip install https://github.com/wq/wq.db/archive/master.zip
>```
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/wq/wq/issues/30#issuecomment-390786316

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by chlarsen** [comment]
Dear Andrew,
I have tried and tested you fix, and the set up procedure now works like a charm, using Python 3.6 on OpenBSD. Thank you so much!
