### ISSUE TITLE
wq addform error

### ISSUE THREAD

**Issue by chlarsen** [wq/wq#33]

**Comment by chlarsen** [comment]
Dear Andrew,
When trying to add and XLS Form to wq.io using wq addform, I get this:
````
wq addform ./labnet.xlsx
Migrations for 'labnet':
  labnet/migrations/0001_initial.py
    - Create model GroupInstitution
    - Create model GroupLocation
    - Create model GroupNote
    - Create model GroupRepondent
    - Create model Labnet
    - Add field labnet to grouprepondent
    - Add field labnet to groupnote
    - Add field labnet to grouplocation
    - Add field labnet to groupinstitution
Update database schema? [Y/n]: 
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, labnet, rest, sessions
Running migrations:
  Applying labnet.0001_initial...Traceback (most recent call last):
  File "/usr/local/wq/lib/python3.6/site-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
psycopg2.InternalError: could not load library "/usr/local/lib/postgresql/postgis-2.2.so": dlopen (/usr/local/lib/postgresql/postgis-2.2.so) failed: Shared object "libproj.so.12" not found, required by "postgis-2.2.so"
LINE 1: ...tion_on_site" varchar(3) NOT NULL, "location_gps" geometry(P...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/wq/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/wq/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/wq/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/wq/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/usr/local/wq/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    fake_initial=fake_initial,
  File "/usr/local/wq/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/wq/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/wq/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/wq/lib/python3.6/site-packages/django/db/migrations/migration.py", line 122, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/wq/lib/python3.6/site-packages/django/db/migrations/operations/models.py", line 92, in database_forwards
    schema_editor.create_model(model)
  File "/usr/local/wq/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 314, in create_model
    self.execute(sql, params or None)
  File "/usr/local/wq/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 133, in execute
    cursor.execute(sql, params)
  File "/usr/local/wq/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/usr/local/wq/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/wq/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/wq/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/wq/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/wq/lib/python3.6/site-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
django.db.utils.InternalError: could not load library "/usr/local/lib/postgresql/postgis-2.2.so": dlopen (/usr/local/lib/postgresql/postgis-2.2.so) failed: Shared object "libproj.so.12" not found, required by "postgis-2.2.so"
LINE 1: ...tion_on_site" varchar(3) NOT NULL, "location_gps" geometry(P...
````
This is a bit weird, because PostGIS and therefore PostgreSQL should not be a dependency at all. I am running an updated freeBSD 10.3 with wq inside a virtualenv courtesy of Python 3.6. Any idea what might be wrong?
Chris

**Comment by chlarsen** [comment]
Solved. It turned out that Django issues the above error messages originating from the (remote) PostgreSQL server, as if they were issues with locally installed libraries. A bit confusing. Solved by fixing an upgrade-induced regression on the database server.
