### ISSUE TITLE
pip Install fails outside venv

### ISSUE THREAD

**Issue by jeremiahsa** [wq/wq#42]
When following the install steps for wq on Ubuntu 18, I hit the issue below. 

A couple of recommendations for the documentation. 
1. "pip install --upgrade pip" breaks pip for this distribution. I had to delete pip and install python3-pip instead. 
2. "pip3 install wq" was then successful in installing wq under python3. 

This is probably only an issue when installing without a venv. 

```pytb
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Baggc4/wq.app/setup.py", line 118, in <module>
        'CI': 'https://travis-ci.org/wq/wq.app',
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-Baggc4/wq.app/setup.py", line 15, in run
        super().run()
    TypeError: super() takes at least 1 argument (0 given)
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Baggc4/wq.app/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-1gKrxS-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-Baggc4/wq.app/

```

**Comment by sheppard** [comment]
Yes, the instructions assume they are run within a venv.  Outside of a venv, the default is for `python` and `pip` to map to Python 2.  wq.app does not currently install on Python 2 (this can be fixed, but should probably just be more clearly documented).

Within an activated venv, the `python` and `pip` commands map to the version of Python within the venv (which is always 3).  That said, we can update the documentation with commands that will work in either case.  In that case think the recommended syntax is:
```bash
python3 -m pip install ...
```

This also makes it easier to upgrade pip on Windows (where apparently `pip install --upgrade pip` will fail even in a venv).

**Comment by sheppard** [comment]
This is better documented now.
