### ISSUE TITLE
Problem with install - AttributeError: module 'wq.db' has no attribute 'rest'

### ISSUE THREAD

**Issue by PeteEmbleton** [wq/wq#49]
Following the instructions here - https://wq.io/1.2/docs/setup-ubuntu only installing on ubuntu 18.04 with postgres 10.
when i get to ./manage.py migrate
i get errors;
/var/www/wq/myproject/db$ ./manage.py migrate
Traceback (most recent call last):
  File "/var/www/wq/myproject/venv/lib/python3.6/site-packages/django/apps/config.py", line 118, in create
    cls = getattr(mod, cls_name)
AttributeError: module 'wq.db' has no attribute 'rest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/wq/myproject/venv/lib/python3.6/site-packages/rest_framework/settings.py", line 177, in import_from_string
    return import_string(val)
  File "/var/www/wq/myproject/venv/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/www/wq/myproject/venv/lib/python3.6/site-packages/wq/db/rest/filters.py", line 2, in <module>
    from django.db.models.fields import FieldDoesNotExist
ImportError: cannot import name 'FieldDoesNotExist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/wq/myproject/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/var/www/wq/myproject/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/var/www/wq/myproject/venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/www/wq/myproject/venv/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/var/www/wq/myproject/venv/lib/python3.6/site-packages/django/apps/config.py", line 136, in create
    import_module(entry)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/www/wq/myproject/venv/lib/python3.6/site-packages/wq/db/rest/__init__.py", line 2, in <module>
    from .routers import ModelRouter, router
  File "/var/www/wq/myproject/venv/lib/python3.6/site-packages/wq/db/rest/routers.py", line 13, in <module>
    from .views import SimpleViewSet, ModelViewSet
  File "/var/www/wq/myproject/venv/lib/python3.6/site-packages/wq/db/rest/views.py", line 1, in <module>
    from rest_framework.generics import GenericAPIView as RestGenericAPIView
  File "/var/www/wq/myproject/venv/lib/python3.6/site-packages/rest_framework/generics.py", line 24, in <module>
    class GenericAPIView(views.APIView):
  File "/var/www/wq/myproject/venv/lib/python3.6/site-packages/rest_framework/generics.py", line 43, in GenericAPIView
    filter_backends = api_settings.DEFAULT_FILTER_BACKENDS
  File "/var/www/wq/myproject/venv/lib/python3.6/site-packages/rest_framework/settings.py", line 220, in __getattr__
    val = perform_import(val, attr)
  File "/var/www/wq/myproject/venv/lib/python3.6/site-packages/rest_framework/settings.py", line 168, in perform_import
    return [import_from_string(item, setting_name) for item in val]
  File "/var/www/wq/myproject/venv/lib/python3.6/site-packages/rest_framework/settings.py", line 168, in <listcomp>
    return [import_from_string(item, setting_name) for item in val]
  File "/var/www/wq/myproject/venv/lib/python3.6/site-packages/rest_framework/settings.py", line 180, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'wq.db.rest.filters.FilterBackend' for API setting 'DEFAULT_FILTER_BACKENDS'. ImportError: cannot import name 'FieldDoesNotExist'.

i have checked that wq.db is installedand the rest api is enabled in the installed applicaitons

**Comment by sheppard** [comment]
What version of Django are you using?  It looks like there is an incompatibility with newer versions.
